/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AdminLayoutRouteImport } from './pages/admin/layout'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as ErrorNotFoundRouteImport } from './pages/_error/not-found'
import { Route as PublicProfileIndexRouteImport } from './pages/_public/profile/index'
import { Route as PublicProductsIndexRouteImport } from './pages/_public/products/index'
import { Route as PublicCheckoutIndexRouteImport } from './pages/_public/checkout/index'
import { Route as PublicCartIndexRouteImport } from './pages/_public/cart/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AuthPasswordRecoveryIndexRouteImport } from './pages/_auth/password-recovery/index'
import { Route as AdminPrimaryProductsIndexRouteImport } from './pages/admin/_primary/products/index'
import { Route as AdminPrimaryPaymentsIndexRouteImport } from './pages/admin/_primary/payments/index'
import { Route as AdminPrimaryOrdersIndexRouteImport } from './pages/admin/_primary/orders/index'
import { Route as AdminPrimaryClientsIndexRouteImport } from './pages/admin/_primary/clients/index'
import { Route as AdminPrimaryAdminsIndexRouteImport } from './pages/admin/_primary/admins/index'
import { Route as AdminOverviewDashboardIndexRouteImport } from './pages/admin/_overview/dashboard/index'
import { Route as PublicProductsProductIdIndexRouteImport } from './pages/_public/products/$productId/index'
import { Route as AuthPasswordRecoveryResetIndexRouteImport } from './pages/_auth/password-recovery/reset/index'
import { Route as AdminPrimaryProductsProductIdIndexRouteImport } from './pages/admin/_primary/products/$productId/index'
import { Route as AdminPrimaryPaymentsPaymentIdIndexRouteImport } from './pages/admin/_primary/payments/$paymentId/index'
import { Route as AdminPrimaryOrdersOrderIdIndexRouteImport } from './pages/admin/_primary/orders/$orderId/index'
import { Route as AdminPrimaryClientsClientIdIndexRouteImport } from './pages/admin/_primary/clients/$clientId/index'
import { Route as AdminPrimaryAdminsAdminIdIndexRouteImport } from './pages/admin/_primary/admins/$adminId/index'

const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ErrorNotFoundRoute = ErrorNotFoundRouteImport.update({
  id: '/_error/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfileIndexRoute = PublicProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicCheckoutIndexRoute = PublicCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicCartIndexRoute = PublicCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordRecoveryIndexRoute =
  AuthPasswordRecoveryIndexRouteImport.update({
    id: '/_auth/password-recovery/',
    path: '/password-recovery/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPrimaryProductsIndexRoute =
  AdminPrimaryProductsIndexRouteImport.update({
    id: '/_primary/products/',
    path: '/products/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryPaymentsIndexRoute =
  AdminPrimaryPaymentsIndexRouteImport.update({
    id: '/_primary/payments/',
    path: '/payments/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryOrdersIndexRoute = AdminPrimaryOrdersIndexRouteImport.update({
  id: '/_primary/orders/',
  path: '/orders/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminPrimaryClientsIndexRoute =
  AdminPrimaryClientsIndexRouteImport.update({
    id: '/_primary/clients/',
    path: '/clients/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryAdminsIndexRoute = AdminPrimaryAdminsIndexRouteImport.update({
  id: '/_primary/admins/',
  path: '/admins/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminOverviewDashboardIndexRoute =
  AdminOverviewDashboardIndexRouteImport.update({
    id: '/_overview/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const PublicProductsProductIdIndexRoute =
  PublicProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AuthPasswordRecoveryResetIndexRoute =
  AuthPasswordRecoveryResetIndexRouteImport.update({
    id: '/_auth/password-recovery/reset/',
    path: '/password-recovery/reset/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPrimaryProductsProductIdIndexRoute =
  AdminPrimaryProductsProductIdIndexRouteImport.update({
    id: '/_primary/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryPaymentsPaymentIdIndexRoute =
  AdminPrimaryPaymentsPaymentIdIndexRouteImport.update({
    id: '/_primary/payments/$paymentId/',
    path: '/payments/$paymentId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryOrdersOrderIdIndexRoute =
  AdminPrimaryOrdersOrderIdIndexRouteImport.update({
    id: '/_primary/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryClientsClientIdIndexRoute =
  AdminPrimaryClientsClientIdIndexRouteImport.update({
    id: '/_primary/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryAdminsAdminIdIndexRoute =
  AdminPrimaryAdminsAdminIdIndexRouteImport.update({
    id: '/_primary/admins/$adminId/',
    path: '/admins/$adminId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/not-found': typeof ErrorNotFoundRoute
  '/admin/': typeof AdminIndexRoute
  '/password-recovery/': typeof AuthPasswordRecoveryIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/cart/': typeof PublicCartIndexRoute
  '/checkout/': typeof PublicCheckoutIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/profile/': typeof PublicProfileIndexRoute
  '/password-recovery/reset/': typeof AuthPasswordRecoveryResetIndexRoute
  '/products/$productId/': typeof PublicProductsProductIdIndexRoute
  '/admin/dashboard/': typeof AdminOverviewDashboardIndexRoute
  '/admin/admins/': typeof AdminPrimaryAdminsIndexRoute
  '/admin/clients/': typeof AdminPrimaryClientsIndexRoute
  '/admin/orders/': typeof AdminPrimaryOrdersIndexRoute
  '/admin/payments/': typeof AdminPrimaryPaymentsIndexRoute
  '/admin/products/': typeof AdminPrimaryProductsIndexRoute
  '/admin/admins/$adminId/': typeof AdminPrimaryAdminsAdminIdIndexRoute
  '/admin/clients/$clientId/': typeof AdminPrimaryClientsClientIdIndexRoute
  '/admin/orders/$orderId/': typeof AdminPrimaryOrdersOrderIdIndexRoute
  '/admin/payments/$paymentId/': typeof AdminPrimaryPaymentsPaymentIdIndexRoute
  '/admin/products/$productId/': typeof AdminPrimaryProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof ErrorNotFoundRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/password-recovery': typeof AuthPasswordRecoveryIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/cart': typeof PublicCartIndexRoute
  '/checkout': typeof PublicCheckoutIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/profile': typeof PublicProfileIndexRoute
  '/password-recovery/reset': typeof AuthPasswordRecoveryResetIndexRoute
  '/products/$productId': typeof PublicProductsProductIdIndexRoute
  '/admin/dashboard': typeof AdminOverviewDashboardIndexRoute
  '/admin/admins': typeof AdminPrimaryAdminsIndexRoute
  '/admin/clients': typeof AdminPrimaryClientsIndexRoute
  '/admin/orders': typeof AdminPrimaryOrdersIndexRoute
  '/admin/payments': typeof AdminPrimaryPaymentsIndexRoute
  '/admin/products': typeof AdminPrimaryProductsIndexRoute
  '/admin/admins/$adminId': typeof AdminPrimaryAdminsAdminIdIndexRoute
  '/admin/clients/$clientId': typeof AdminPrimaryClientsClientIdIndexRoute
  '/admin/orders/$orderId': typeof AdminPrimaryOrdersOrderIdIndexRoute
  '/admin/payments/$paymentId': typeof AdminPrimaryPaymentsPaymentIdIndexRoute
  '/admin/products/$productId': typeof AdminPrimaryProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/_error/not-found': typeof ErrorNotFoundRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/password-recovery/': typeof AuthPasswordRecoveryIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_public/cart/': typeof PublicCartIndexRoute
  '/_public/checkout/': typeof PublicCheckoutIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/profile/': typeof PublicProfileIndexRoute
  '/_auth/password-recovery/reset/': typeof AuthPasswordRecoveryResetIndexRoute
  '/_public/products/$productId/': typeof PublicProductsProductIdIndexRoute
  '/admin/_overview/dashboard/': typeof AdminOverviewDashboardIndexRoute
  '/admin/_primary/admins/': typeof AdminPrimaryAdminsIndexRoute
  '/admin/_primary/clients/': typeof AdminPrimaryClientsIndexRoute
  '/admin/_primary/orders/': typeof AdminPrimaryOrdersIndexRoute
  '/admin/_primary/payments/': typeof AdminPrimaryPaymentsIndexRoute
  '/admin/_primary/products/': typeof AdminPrimaryProductsIndexRoute
  '/admin/_primary/admins/$adminId/': typeof AdminPrimaryAdminsAdminIdIndexRoute
  '/admin/_primary/clients/$clientId/': typeof AdminPrimaryClientsClientIdIndexRoute
  '/admin/_primary/orders/$orderId/': typeof AdminPrimaryOrdersOrderIdIndexRoute
  '/admin/_primary/payments/$paymentId/': typeof AdminPrimaryPaymentsPaymentIdIndexRoute
  '/admin/_primary/products/$productId/': typeof AdminPrimaryProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/not-found'
    | '/admin/'
    | '/password-recovery/'
    | '/sign-in/'
    | '/sign-up/'
    | '/cart/'
    | '/checkout/'
    | '/products/'
    | '/profile/'
    | '/password-recovery/reset/'
    | '/products/$productId/'
    | '/admin/dashboard/'
    | '/admin/admins/'
    | '/admin/clients/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/products/'
    | '/admin/admins/$adminId/'
    | '/admin/clients/$clientId/'
    | '/admin/orders/$orderId/'
    | '/admin/payments/$paymentId/'
    | '/admin/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/'
    | '/admin'
    | '/password-recovery'
    | '/sign-in'
    | '/sign-up'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/profile'
    | '/password-recovery/reset'
    | '/products/$productId'
    | '/admin/dashboard'
    | '/admin/admins'
    | '/admin/clients'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/admins/$adminId'
    | '/admin/clients/$clientId'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/admin/products/$productId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_error/not-found'
    | '/_public/'
    | '/admin/'
    | '/_auth/password-recovery/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_public/cart/'
    | '/_public/checkout/'
    | '/_public/products/'
    | '/_public/profile/'
    | '/_auth/password-recovery/reset/'
    | '/_public/products/$productId/'
    | '/admin/_overview/dashboard/'
    | '/admin/_primary/admins/'
    | '/admin/_primary/clients/'
    | '/admin/_primary/orders/'
    | '/admin/_primary/payments/'
    | '/admin/_primary/products/'
    | '/admin/_primary/admins/$adminId/'
    | '/admin/_primary/clients/$clientId/'
    | '/admin/_primary/orders/$orderId/'
    | '/admin/_primary/payments/$paymentId/'
    | '/admin/_primary/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ErrorNotFoundRoute: typeof ErrorNotFoundRoute
  AuthPasswordRecoveryIndexRoute: typeof AuthPasswordRecoveryIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthPasswordRecoveryResetIndexRoute: typeof AuthPasswordRecoveryResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_error/not-found': {
      id: '/_error/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof ErrorNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/profile/': {
      id: '/_public/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PublicProfileIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/checkout/': {
      id: '/_public/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof PublicCheckoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/cart/': {
      id: '/_public/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof PublicCartIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/password-recovery/': {
      id: '/_auth/password-recovery/'
      path: '/password-recovery'
      fullPath: '/password-recovery/'
      preLoaderRoute: typeof AuthPasswordRecoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_primary/products/': {
      id: '/admin/_primary/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminPrimaryProductsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/payments/': {
      id: '/admin/_primary/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPrimaryPaymentsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/orders/': {
      id: '/admin/_primary/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminPrimaryOrdersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/clients/': {
      id: '/admin/_primary/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminPrimaryClientsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/admins/': {
      id: '/admin/_primary/admins/'
      path: '/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof AdminPrimaryAdminsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_overview/dashboard/': {
      id: '/admin/_overview/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminOverviewDashboardIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/products/$productId/': {
      id: '/_public/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof PublicProductsProductIdIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/password-recovery/reset/': {
      id: '/_auth/password-recovery/reset/'
      path: '/password-recovery/reset'
      fullPath: '/password-recovery/reset/'
      preLoaderRoute: typeof AuthPasswordRecoveryResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_primary/products/$productId/': {
      id: '/admin/_primary/products/$productId/'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId/'
      preLoaderRoute: typeof AdminPrimaryProductsProductIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/payments/$paymentId/': {
      id: '/admin/_primary/payments/$paymentId/'
      path: '/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId/'
      preLoaderRoute: typeof AdminPrimaryPaymentsPaymentIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/orders/$orderId/': {
      id: '/admin/_primary/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId/'
      preLoaderRoute: typeof AdminPrimaryOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/clients/$clientId/': {
      id: '/admin/_primary/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId/'
      preLoaderRoute: typeof AdminPrimaryClientsClientIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/admins/$adminId/': {
      id: '/admin/_primary/admins/$adminId/'
      path: '/admins/$adminId'
      fullPath: '/admin/admins/$adminId/'
      preLoaderRoute: typeof AdminPrimaryAdminsAdminIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCartIndexRoute: typeof PublicCartIndexRoute
  PublicCheckoutIndexRoute: typeof PublicCheckoutIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicProfileIndexRoute: typeof PublicProfileIndexRoute
  PublicProductsProductIdIndexRoute: typeof PublicProductsProductIdIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCartIndexRoute: PublicCartIndexRoute,
  PublicCheckoutIndexRoute: PublicCheckoutIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicProfileIndexRoute: PublicProfileIndexRoute,
  PublicProductsProductIdIndexRoute: PublicProductsProductIdIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOverviewDashboardIndexRoute: typeof AdminOverviewDashboardIndexRoute
  AdminPrimaryAdminsIndexRoute: typeof AdminPrimaryAdminsIndexRoute
  AdminPrimaryClientsIndexRoute: typeof AdminPrimaryClientsIndexRoute
  AdminPrimaryOrdersIndexRoute: typeof AdminPrimaryOrdersIndexRoute
  AdminPrimaryPaymentsIndexRoute: typeof AdminPrimaryPaymentsIndexRoute
  AdminPrimaryProductsIndexRoute: typeof AdminPrimaryProductsIndexRoute
  AdminPrimaryAdminsAdminIdIndexRoute: typeof AdminPrimaryAdminsAdminIdIndexRoute
  AdminPrimaryClientsClientIdIndexRoute: typeof AdminPrimaryClientsClientIdIndexRoute
  AdminPrimaryOrdersOrderIdIndexRoute: typeof AdminPrimaryOrdersOrderIdIndexRoute
  AdminPrimaryPaymentsPaymentIdIndexRoute: typeof AdminPrimaryPaymentsPaymentIdIndexRoute
  AdminPrimaryProductsProductIdIndexRoute: typeof AdminPrimaryProductsProductIdIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOverviewDashboardIndexRoute: AdminOverviewDashboardIndexRoute,
  AdminPrimaryAdminsIndexRoute: AdminPrimaryAdminsIndexRoute,
  AdminPrimaryClientsIndexRoute: AdminPrimaryClientsIndexRoute,
  AdminPrimaryOrdersIndexRoute: AdminPrimaryOrdersIndexRoute,
  AdminPrimaryPaymentsIndexRoute: AdminPrimaryPaymentsIndexRoute,
  AdminPrimaryProductsIndexRoute: AdminPrimaryProductsIndexRoute,
  AdminPrimaryAdminsAdminIdIndexRoute: AdminPrimaryAdminsAdminIdIndexRoute,
  AdminPrimaryClientsClientIdIndexRoute: AdminPrimaryClientsClientIdIndexRoute,
  AdminPrimaryOrdersOrderIdIndexRoute: AdminPrimaryOrdersOrderIdIndexRoute,
  AdminPrimaryPaymentsPaymentIdIndexRoute:
    AdminPrimaryPaymentsPaymentIdIndexRoute,
  AdminPrimaryProductsProductIdIndexRoute:
    AdminPrimaryProductsProductIdIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ErrorNotFoundRoute: ErrorNotFoundRoute,
  AuthPasswordRecoveryIndexRoute: AuthPasswordRecoveryIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthPasswordRecoveryResetIndexRoute: AuthPasswordRecoveryResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
