/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AdminLayoutRouteImport } from './pages/admin/layout'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as ErrorNotFoundRouteImport } from './pages/_error/not-found'
import { Route as AdminProductsIndexRouteImport } from './pages/admin/products/index'
import { Route as PublicProductsIndexRouteImport } from './pages/_public/products/index'
import { Route as PublicCheckoutIndexRouteImport } from './pages/_public/checkout/index'
import { Route as PublicCartIndexRouteImport } from './pages/_public/cart/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AdminOverviewDashboardIndexRouteImport } from './pages/admin/_overview/dashboard/index'
import { Route as PublicProductsProductIdIndexRouteImport } from './pages/_public/products/$productId/index'

const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ErrorNotFoundRoute = ErrorNotFoundRouteImport.update({
  id: '/_error/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicCheckoutIndexRoute = PublicCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicCartIndexRoute = PublicCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewDashboardIndexRoute =
  AdminOverviewDashboardIndexRouteImport.update({
    id: '/_overview/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const PublicProductsProductIdIndexRoute =
  PublicProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/not-found': typeof ErrorNotFoundRoute
  '/admin/': typeof AdminIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/cart/': typeof PublicCartIndexRoute
  '/checkout/': typeof PublicCheckoutIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/products/$productId/': typeof PublicProductsProductIdIndexRoute
  '/admin/dashboard/': typeof AdminOverviewDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof ErrorNotFoundRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/cart': typeof PublicCartIndexRoute
  '/checkout': typeof PublicCheckoutIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/products/$productId': typeof PublicProductsProductIdIndexRoute
  '/admin/dashboard': typeof AdminOverviewDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/_error/not-found': typeof ErrorNotFoundRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_public/cart/': typeof PublicCartIndexRoute
  '/_public/checkout/': typeof PublicCheckoutIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/_public/products/$productId/': typeof PublicProductsProductIdIndexRoute
  '/admin/_overview/dashboard/': typeof AdminOverviewDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/not-found'
    | '/admin/'
    | '/sign-in/'
    | '/sign-up/'
    | '/cart/'
    | '/checkout/'
    | '/products/'
    | '/admin/products/'
    | '/products/$productId/'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/admin/products'
    | '/products/$productId'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_error/not-found'
    | '/_public/'
    | '/admin/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_public/cart/'
    | '/_public/checkout/'
    | '/_public/products/'
    | '/admin/products/'
    | '/_public/products/$productId/'
    | '/admin/_overview/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ErrorNotFoundRoute: typeof ErrorNotFoundRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_error/not-found': {
      id: '/_error/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof ErrorNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/checkout/': {
      id: '/_public/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof PublicCheckoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/cart/': {
      id: '/_public/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof PublicCartIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_overview/dashboard/': {
      id: '/admin/_overview/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminOverviewDashboardIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/products/$productId/': {
      id: '/_public/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof PublicProductsProductIdIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCartIndexRoute: typeof PublicCartIndexRoute
  PublicCheckoutIndexRoute: typeof PublicCheckoutIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicProductsProductIdIndexRoute: typeof PublicProductsProductIdIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCartIndexRoute: PublicCartIndexRoute,
  PublicCheckoutIndexRoute: PublicCheckoutIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicProductsProductIdIndexRoute: PublicProductsProductIdIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminOverviewDashboardIndexRoute: typeof AdminOverviewDashboardIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminOverviewDashboardIndexRoute: AdminOverviewDashboardIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ErrorNotFoundRoute: ErrorNotFoundRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
