export interface OrderStatus {
  PENDING: "PENDING";
  PAYMENT_PENDING: "PAYMENT_PENDING";
  PAYMENT_APPROVED: "PAYMENT_APPROVED";
  PROCESSING: "PROCESSING";
  SHIPPED: "SHIPPED";
  DELIVERED: "DELIVERED";
  CANCELLED: "CANCELLED";
  REFUNDED: "REFUNDED";
}
