export interface PaymentStatus {
  PENDING: "PENDING";
  APPROVED: "APPROVED";
  REJECTED: "REJECTED";
  IN_PROCESS: "IN_PROCESS";
  CANCELLED: "CANCELLED";
  REFUNDED: "REFUNDED";
  CHARGED_BACK: "CHARGED_BACK";
}
